config/routes.rb
TorreCentenario::Application.routes.draw do
  resources :activities

  resources :referrals do
    match 'create_batch', :on => :collection
    match 'accept', :on => :collection
  end

  resources :clues do
		match 'assign_tickets', :on => :collection
    match 'activate_web'
    match 'activate'
    match 'deactivate'
	end

  resources :tickets do
    match 'assign_to_user', :on => :collection
  end

  resources :roles

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
	  get 'logout', :to => "devise/sessions#destroy", :as => :logout
	  get 'signin', :to => "devise/sessions#new", :as => :signin
	  get 'signup', :to => "devise/registrations#new", :as => :signup
  end

  resources :users do
    match 'synch'
  end
	
  get 'admin', :to => "admin#index", :as => :admin_index
  
  get 'admin/logout', :to => "admin#logout", :as => :admin_logout

  get 'admin/create_clue_mobile', :to => "admin#create_clue_mobile", :as => :admin_create_clue_mobile
	
  get 'admin/create_clue_web', :to => "admin#create_clue_web", :as => :admin_create_clue_web
	
  get 'admin/edit_clue_mobile/:id', :to => "admin#edit_clue_mobile", :as => :admin_edit_clue_mobile
  
  get 'admin/edit_clue_web/:id', :to => "admin#edit_clue_web", :as => :admin_edit_clue_web

  get 'admin/users_referrals', :to => "admin#users_referrals", :as => :admin_users_referrals

  get 'admin/clues_list_mobile', :to => "admin#clues_list_mobile", :as => :admin_clues_list_mobile

  get 'admin/clues_list_web', :to => "admin#clues_list_web", :as => :admin_clues_list_web

  get 'admin/reports', :to => "admin#reports", :as => :admin_reports
  
  get 'admin/reports_summary', :to => "admin#reports_summary", :as => :admin_reports_summary
  
  get 'admin/reports_users', :to => "admin#reports_users", :as => :admin_reports_users
  
  get 'admin/reports_winners', :to => "admin#reports_winners", :as => :admin_reports_winners

  match 'search_clue' => 'display#search_clue', :as => :search_clue

  match 'make_guess' => 'display#make_guess', :as => :make_guess

  match 'invite_friends' => 'display#invite_friends', :as => :invite_friends
  
  match 'fun_facts' => 'display#fun_facts', :as => :fun_facts

  match 'martin_facts' => 'display#martin_facts', :as => :martin_facts

  match 'mobile/' => 'mobile#index', :as => :mobile

  match 'mobile/search_ticket' => 'mobile#search_ticket', :as => :mobile_search_ticket

  match 'mobile/new_fan' => 'mobile#new_fan', :as => :mobile_new_fan

  match 'terms_and_conditions' => 'display#terms_and_conditions', :as => :terms_and_conditions

  match 'youtube_channel' => 'display#youtube_channel', :as => :youtube_channel

  get 'check_availability' => 'display#check_availability', :as => :check_availability

  root :to => 'display#index'

end

app/models/referral.rb
class Referral < ActiveRecord::Base
  attr_accessible :accepted, :referred_uid, :user_id
	belongs_to :user
	belongs_to :referred, :class_name => "User", :foreign_key => :referred_uid, :primary_key => :uid

  def self.create_batch referrals
    referrals.each do |referral|
      begin
        Referral.create(referral)
      rescue
        logger.error("Non unique referral for user_id:#{referral['user_id']} and referred_uid:#{referral['referred_uid']}")
      end
    end
  end

	def self.accept user_uid, referred_id
    origin_user = User.find_by_uid(user_uid)
    referred_user = User.find(referred_id)
    referral = Referral.find_by_user_id_and_referred_uid(origin_user.id, referred_user.uid)
    if referral
		  referral.update_attribute(:accepted, true)
  		referred_user.update_attribute(:referred_user_id, origin_user.id)
    else
      raise "No referral found for user_uid:#{user_uid} and referred_id:#{referred_id}"
    end
	end

	def self.find_top_referrers result_size
    #TODO: Insert custom query that gets the number of accepted referrals on the fly
		#User.where("ticket_id is null").order("friend_count desc").limit(result_size)
    Referral.joins(:user).select("user_id, count(user_id) as referral_count").where("accepted = ? AND users.ticket_id is null", true).group("user_id").order("referral_count DESC").limit(20)
	end

end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  
  authorize_resource

  # GET /referrals
  # GET /referrals.json
  def index
    @referrals = Referral.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @referrals }
    end
  end

  # GET /referrals/1
  # GET /referrals/1.json
  def show
    @referral = Referral.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @referral }
    end
  end

  # GET /referrals/new
  # GET /referrals/new.json
  def new
    @referral = Referral.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @referral }
    end
  end

  # GET /referrals/1/edit
  def edit
    @referral = Referral.find(params[:id])
  end

  # POST /referrals
  # POST /referrals.json
  def create
    @referral = Referral.new(params[:referral])

    respond_to do |format|
      if @referral.save
        format.html { redirect_to @referral, notice: 'referral was successfully created.' }
        format.json { render json: @referral, status: :created, location: @referral }
      else
        format.html { render action: "new" }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /referrals/1
  # PUT /referrals/1.json
  def update
    @referral = Referral.find(params[:id])

    respond_to do |format|
      if @referral.update_attributes(params[:referral])
        format.html { redirect_to @referral, notice: 'referral was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referrals/1
  # DELETE /referrals/1.json
  def destroy
    @referral = Referral.find(params[:id])
    @referral.destroy

    respond_to do |format|
      format.html { redirect_to referrals_url }
      format.json { head :no_content }
    end
  end

  def create_batch
    @referrals = Referral.create_batch params[:referrals]
    
    respond_to do |format|
      format.json { render json: @referrals}
    end
  end

  def accept
    @referral = Referral.accept params[:origin_user_uid], params[:referred_user_id]
  
    respond_to do |format|
      format.json { render json: @referral}
    end
  end

end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/referrals/_form.html.erb
<%= form_for(@referral) do |f| %>
  <% if @referral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@referral.errors.count, "error") %> prohibited this referral from being saved:</h2>

      <ul>
      <% @referral.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :referred_uid %><br />
    <%= f.number_field :referred_uid %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br />
    <%= f.check_box :accepted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/referrals/edit.html.erb
<h1>Editing referral</h1>

<%= render 'form' %>

<%= link_to 'Show', @referral %> |
<%= link_to 'Back', referrals_path %>

app/views/referrals/index.html.erb
<h1>Listing referrals</h1>

<table>
  <tr>
    <th>User</th>
    <th>Referred uid</th>
    <th>Accepted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @referrals.each do |referral| %>
  <tr>
    <td><%= referral.user_id %></td>
    <td><%= referral.referred_uid %></td>
    <td><%= referral.accepted %></td>
    <td><%= link_to 'Show', referral %></td>
    <td><%= link_to 'Edit', edit_referral_path(referral) %></td>
    <td><%= link_to 'Destroy', referral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New referral', new_referral_path %>

app/views/referrals/new.html.erb
<h1>New referral</h1>

<%= render 'form' %>

<%= link_to 'Back', referrals_path %>

app/views/referrals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @referral.user_id %>
</p>

<p>
  <b>Referred uid:</b>
  <%= @referral.referred_uid %>
</p>

<p>
  <b>Accepted:</b>
  <%= @referral.accepted %>
</p>


<%= link_to 'Edit', edit_referral_path(@referral) %> |
<%= link_to 'Back', referrals_path %>