config/routes.rb
TorreCentenario::Application.routes.draw do
  resources :activities

  resources :referrals do
    match 'create_batch', :on => :collection
    match 'accept', :on => :collection
  end

  resources :clues do
		match 'assign_tickets', :on => :collection
    match 'activate_web'
    match 'activate'
    match 'deactivate'
	end

  resources :tickets do
    match 'assign_to_user', :on => :collection
  end

  resources :roles

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
	  get 'logout', :to => "devise/sessions#destroy", :as => :logout
	  get 'signin', :to => "devise/sessions#new", :as => :signin
	  get 'signup', :to => "devise/registrations#new", :as => :signup
  end

  resources :users do
    match 'synch'
  end
	
  get 'admin', :to => "admin#index", :as => :admin_index
  
  get 'admin/logout', :to => "admin#logout", :as => :admin_logout

  get 'admin/create_clue_mobile', :to => "admin#create_clue_mobile", :as => :admin_create_clue_mobile
	
  get 'admin/create_clue_web', :to => "admin#create_clue_web", :as => :admin_create_clue_web
	
  get 'admin/edit_clue_mobile/:id', :to => "admin#edit_clue_mobile", :as => :admin_edit_clue_mobile
  
  get 'admin/edit_clue_web/:id', :to => "admin#edit_clue_web", :as => :admin_edit_clue_web

  get 'admin/users_referrals', :to => "admin#users_referrals", :as => :admin_users_referrals

  get 'admin/clues_list_mobile', :to => "admin#clues_list_mobile", :as => :admin_clues_list_mobile

  get 'admin/clues_list_web', :to => "admin#clues_list_web", :as => :admin_clues_list_web

  get 'admin/reports', :to => "admin#reports", :as => :admin_reports
  
  get 'admin/reports_summary', :to => "admin#reports_summary", :as => :admin_reports_summary
  
  get 'admin/reports_users', :to => "admin#reports_users", :as => :admin_reports_users
  
  get 'admin/reports_winners', :to => "admin#reports_winners", :as => :admin_reports_winners

  match 'search_clue' => 'display#search_clue', :as => :search_clue

  match 'make_guess' => 'display#make_guess', :as => :make_guess

  match 'invite_friends' => 'display#invite_friends', :as => :invite_friends
  
  match 'fun_facts' => 'display#fun_facts', :as => :fun_facts

  match 'martin_facts' => 'display#martin_facts', :as => :martin_facts

  match 'mobile/' => 'mobile#index', :as => :mobile

  match 'mobile/search_ticket' => 'mobile#search_ticket', :as => :mobile_search_ticket

  match 'mobile/new_fan' => 'mobile#new_fan', :as => :mobile_new_fan

  match 'terms_and_conditions' => 'display#terms_and_conditions', :as => :terms_and_conditions

  match 'youtube_channel' => 'display#youtube_channel', :as => :youtube_channel

  get 'check_availability' => 'display#check_availability', :as => :check_availability

  root :to => 'display#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :description
  has_and_belongs_to_many :users
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  authorize_resource

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.description %></td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @activity.description %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>