config/routes.rb
TorreCentenario::Application.routes.draw do
  resources :activities

  resources :referrals do
    match 'create_batch', :on => :collection
    match 'accept', :on => :collection
  end

  resources :clues do
		match 'assign_tickets', :on => :collection
    match 'activate_web'
    match 'activate'
    match 'deactivate'
	end

  resources :tickets do
    match 'assign_to_user', :on => :collection
  end

  resources :roles

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
	  get 'logout', :to => "devise/sessions#destroy", :as => :logout
	  get 'signin', :to => "devise/sessions#new", :as => :signin
	  get 'signup', :to => "devise/registrations#new", :as => :signup
  end

  resources :users do
    match 'synch'
  end
	
  get 'admin', :to => "admin#index", :as => :admin_index
  
  get 'admin/logout', :to => "admin#logout", :as => :admin_logout

  get 'admin/create_clue_mobile', :to => "admin#create_clue_mobile", :as => :admin_create_clue_mobile
	
  get 'admin/create_clue_web', :to => "admin#create_clue_web", :as => :admin_create_clue_web
	
  get 'admin/edit_clue_mobile/:id', :to => "admin#edit_clue_mobile", :as => :admin_edit_clue_mobile
  
  get 'admin/edit_clue_web/:id', :to => "admin#edit_clue_web", :as => :admin_edit_clue_web

  get 'admin/users_referrals', :to => "admin#users_referrals", :as => :admin_users_referrals

  get 'admin/clues_list_mobile', :to => "admin#clues_list_mobile", :as => :admin_clues_list_mobile

  get 'admin/clues_list_web', :to => "admin#clues_list_web", :as => :admin_clues_list_web

  get 'admin/reports', :to => "admin#reports", :as => :admin_reports
  
  get 'admin/reports_summary', :to => "admin#reports_summary", :as => :admin_reports_summary
  
  get 'admin/reports_users', :to => "admin#reports_users", :as => :admin_reports_users
  
  get 'admin/reports_winners', :to => "admin#reports_winners", :as => :admin_reports_winners

  match 'search_clue' => 'display#search_clue', :as => :search_clue

  match 'make_guess' => 'display#make_guess', :as => :make_guess

  match 'invite_friends' => 'display#invite_friends', :as => :invite_friends
  
  match 'fun_facts' => 'display#fun_facts', :as => :fun_facts

  match 'martin_facts' => 'display#martin_facts', :as => :martin_facts

  match 'mobile/' => 'mobile#index', :as => :mobile

  match 'mobile/search_ticket' => 'mobile#search_ticket', :as => :mobile_search_ticket

  match 'mobile/new_fan' => 'mobile#new_fan', :as => :mobile_new_fan

  match 'terms_and_conditions' => 'display#terms_and_conditions', :as => :terms_and_conditions

  match 'youtube_channel' => 'display#youtube_channel', :as => :youtube_channel

  get 'check_availability' => 'display#check_availability', :as => :check_availability

  root :to => 'display#index'

end

app/models/clue.rb
class Clue < ActiveRecord::Base
  attr_accessible :active, :description, :image_url, :latitude, :longitude, :radius, :source_type, :avatar
  has_attached_file :avatar, :styles => { :medium => "190x190", :thumb => "50x50" }
  after_save :update_image_url
	has_many :tickets
  has_and_belongs_to_many :users
	geocoded_by :description

	def self.active_to_user type
		clues = Clue.find_all_by_active_and_source_type(true, type)
		hidden_clues = []
		clues.each do |clue|
      total_tickets = Ticket.where("clue_id = ?", clue.id)
      remain_tickets = total_tickets.length
      total_tickets.each do |ticket|
        remain_tickets -= 1 if ticket.assigned == true
      end
			hidden_clues << {:id => clue.id, :description => clue.description, :image_url => clue.image_url, :source_type => clue.source_type, 
        :total_tickets => total_tickets.length, :remain_tickets => total_tickets.length - remain_tickets}
		end
		return hidden_clues
	end

	def assign_tickets number
    number = number.to_i
    if self.tickets_not_assigned.count == number
      return
    elsif self.tickets_not_assigned.count > number # delete tickets
      number_to_delete = self.tickets_not_assigned.count - number

      count = 0
      self.tickets_not_assigned.each do |ticket|
        ticket.destroy
        count += 1
        if count == number_to_delete
          break
        end
      end
    else # add tickets
      number_to_add = number - self.tickets_not_assigned.count  
      self.create_tickets number_to_add
    end
	end
  
  def create_tickets number
		number.to_i.times do
			folio = SecureRandom.uuid.slice(0,7)
			self.tickets << Ticket.create(:clue_id => self.id, :source_type => self.source_type, :folio => folio)
		end
  end

  def tickets_not_assigned
    Ticket.joins(:clue).where("clue_id = ? and assigned = ?",self.id , false)
  end

  def tickets_assigned
    Ticket.joins(:clue).where("clue_id = ? and assigned = ?",self.id , true)
  end

  def activate_web
    Clue.update_all("active = false", "source_type = 'web'")
    self.update_attribute(:active, true)
    self
  end

  def activate
    self.update_attribute(:active, true)
    self
  end

  def deactivate
    self.update_attribute(:active, false)
    self
  end

  private

  def update_image_url
    self.update_column(:image_url, self.avatar.url(:medium))
  end
end

app/controllers/clues_controller.rb
class CluesController < ApplicationController
  
  authorize_resource
  
  # GET /clues
  # GET /clues.json
  def index
    @clues = Clue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clues }
    end
  end

  # GET /clues/1
  # GET /clues/1.json
  def show
    @clue = Clue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clue }
    end
  end

  # GET /clues/new
  # GET /clues/new.json
  def new
    @clue = Clue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clue }
    end
  end

  # GET /clues/1/edit
  def edit
    @clue = Clue.find(params[:id])
  end

  # POST /clues
  # POST /clues.json
  def create
    @clue = Clue.new(params[:clue])

    respond_to do |format|
      if @clue.save
        format.html { redirect_to @clue, notice: 'Clue was successfully created.' }
        format.json { render json: @clue, status: :created, location: @clue }
      else
        format.html { render action: "new" }
        format.json { render json: @clue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clues/1
  # PUT /clues/1.json
  def update
    @clue = Clue.find(params[:id])

    respond_to do |format|
      if @clue.update_attributes(params[:clue])
        format.html { redirect_to @clue, notice: 'Clue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clues/1
  # DELETE /clues/1.json
  def destroy
    @clue = Clue.find(params[:id])
    @clue.destroy

    respond_to do |format|
      format.html { redirect_to clues_url }
      format.json { head :no_content }
    end
  end

	def assign_tickets
    if params[:clue][:id].blank?
      @clue = Clue.create(params[:clue])
    else
      @clue = Clue.find(params[:clue][:id])
      @clue.update_attributes(params[:clue])
    end
    @clue.assign_tickets(params[:ticket_number])

		respond_to do |format|
      if @clue.source_type == 'web'
        format.html { redirect_to :admin_clues_list_web }
      elsif @clue.source_type == 'mobile'
        format.html { redirect_to :admin_clues_list_mobile }
      end
			format.json { render json: @clue}
		end
	end
  
  def activate_web
    @clue = Clue.find(params[:clue_id]).activate_web

    respond_to do |format|
      format.json { render json: @clue }
    end
  end

  def activate
    @clue = Clue.find(params[:clue_id]).activate

    respond_to do |format|
      format.json { render json: @clue }
    end
  end

  def deactivate
    @clue = Clue.find(params[:clue_id]).deactivate

    respond_to do |format|
      format.json { render json: @clue }
    end
  end
end

app/helpers/clues_helper.rb
module CluesHelper
end

app/views/clues/_form.html.erb
<%= form_for(@clue) do |f| %>
  <% if @clue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clue.errors.count, "error") %> prohibited this clue from being saved:</h2>

      <ul>
      <% @clue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :radius %><br />
    <%= f.text_field :radius %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clues/edit.html.erb
<h1>Editing clue</h1>

<%= render 'form' %>

<%= link_to 'Show', @clue %> |
<%= link_to 'Back', clues_path %>

app/views/clues/index.html.erb
<h1>Listing clues</h1>

<table>
  <tr>
    <th>Image url</th>
    <th>Description</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Radius</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clues.each do |clue| %>
  <tr>
    <td><%= clue.image_url %></td>
    <td><%= clue.description %></td>
    <td><%= clue.longitude %></td>
    <td><%= clue.latitude %></td>
    <td><%= clue.radius %></td>
    <td><%= clue.active %></td>
    <td><%= link_to 'Show', clue %></td>
    <td><%= link_to 'Edit', edit_clue_path(clue) %></td>
    <td><%= link_to 'Destroy', clue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clue', new_clue_path %>

app/views/clues/new.html.erb
<h1>New clue</h1>

<%= render 'form' %>

<%= link_to 'Back', clues_path %>

app/views/clues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image url:</b>
  <%= @clue.image_url %>
</p>

<p>
  <b>Description:</b>
  <%= @clue.description %>
</p>

<p>
  <b>Longitude:</b>
  <%= @clue.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @clue.latitude %>
</p>

<p>
  <b>Radius:</b>
  <%= @clue.radius %>
</p>

<p>
  <b>Active:</b>
  <%= @clue.active %>
</p>


<%= link_to 'Edit', edit_clue_path(@clue) %> |
<%= link_to 'Back', clues_path %>